
services:
  web:
    build: .
    container_name: eduflow_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=eduflow.settings
    volumes:
      - .:/app
    depends_on:
      - celery_worker

  celery_worker:
    build: .
    container_name: eduflow_celery_worker
    command: celery -A eduflow worker --loglevel=info
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=eduflow.settings
    volumes:
      - .:/app

  celery_beat:
    build: .
    container_name: eduflow_celery_beat
    command: celery -A eduflow beat --loglevel=info
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=eduflow.settings
    volumes:
      - .:/app
    depends_on:
      - celery_worker
