services:
  backend:
    build: .
    container_name: eduflow_web
    command: daphne -b 0.0.0.0 -p 8000 eduflow.asgi:application
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: eduflow.settings
    volumes:
      - .:/app
    depends_on:
      - redis

  realtime:
    build: ../realtime
    container_name: eduflow_realtime
    command: daphne -b 0.0.0.0 -p 8001 realtime_service.asgi:application
    env_file:
      - ../realtime/.env
    volumes:
      - ../realtime:/app
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A eduflow worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis

  celery_beat:
    build: .
    command: celery -A eduflow beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis

  nginx:
    build: ../nginx
    container_name: eduflow_nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - realtime

  redis:
    image: redis:7-alpine

  ai-service:
    build: ../ai-service
    container_name: eduflow-ai
    ports:
      - "8002:8002"
    env_file:
      - ../ai-service/.env
networks:
  eduflow-internal:
    driver: bridge

